package com.vitorxp.WorthClient.manager;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import com.vitorxp.WorthClient.WorthClient;
import com.vitorxp.WorthClient.config.AnimationsConfig;
import com.vitorxp.WorthClient.config.KeystrokesSettings;
import com.vitorxp.WorthClient.hud.FPSHUD;
import com.vitorxp.WorthClient.hud.PingHUD;
import com.vitorxp.WorthClient.hud.ScoreboardHUD;

import java.awt.*;
import java.io.*;

public class ConfigManager {

    private static final File FILE = new File("config/WorthClient/settings.json");

    public static void save() {
        JsonObject obj = new JsonObject();
        obj.addProperty("petBlock", WorthClient.blockPetMessages);
        obj.addProperty("inventoryBlock", WorthClient.blockInventoryMessages);
        obj.addProperty("announceZealot", WorthClient.announceZealot);
        obj.addProperty("MsgBlockDestroyBlock", WorthClient.MsgBlockDestroyBlock);
        obj.addProperty("petOverlay", WorthClient.petOverlay);
        obj.addProperty("pingOverlay", PingHUD.enabled);
        obj.addProperty("pingOverlayscale", PingHUD.scale);
        obj.addProperty("pingOverlaybackground", PingHUD.background);
        obj.addProperty("pingOverlaybackgroundColor", PingHUD.backgroundColor);
        obj.addProperty("pingOverlayborder", PingHUD.border);
        obj.addProperty("pingOverlayborderColor", PingHUD.borderColor);
        obj.addProperty("pingOverlaychroma", PingHUD.chroma);
        obj.addProperty("pingOverlaytextColor", PingHUD.textColor);
        obj.addProperty("pingOverlaytextShadow", PingHUD.textShadow);
        obj.addProperty("fpsOverlay", FPSHUD.enabled);
        obj.addProperty("fpsOverlayscale", FPSHUD.scale);
        obj.addProperty("fpsOverlaybackground", FPSHUD.background);
        obj.addProperty("fpsOverlaybackgroundColor", FPSHUD.backgroundColor);
        obj.addProperty("fpsOverlayborder", FPSHUD.border);
        obj.addProperty("fpsOverlayborderColor", FPSHUD.borderColor);
        obj.addProperty("fpsOverlaychroma", FPSHUD.chroma);
        obj.addProperty("fpsOverlaytextColor", FPSHUD.textColor);
        obj.addProperty("fpsOverlaytextShadow", FPSHUD.textShadow);
        obj.addProperty("mainHandHUDOverlay", WorthClient.mainHandHUDOverlay);
        obj.addProperty("helmetHUDOverlay", WorthClient.helmetHUDOverlay);
        obj.addProperty("chestplateHUDOverlay", WorthClient.chestplateHUDOverlay);
        obj.addProperty("leggingsHUDOverlay", WorthClient.leggingsHUDOverlay);
        obj.addProperty("bootsHUDOverlay", WorthClient.bootsHUDOverlay);
        obj.addProperty("petDisplayViewOff", WorthClient.petDisplayViewOff);
        obj.addProperty("viewsPetAll", WorthClient.viewsPetAll);
        obj.addProperty("showTime", WorthClient.showTime);
        obj.addProperty("enableCopy", WorthClient.enableCopy);
        obj.addProperty("PerspectiveModToggle", WorthClient.PerspectiveModToggle);
        obj.addProperty("ArmorsOverlays", WorthClient.ArmorsOverlays);
        obj.addProperty("RadarOverlay", WorthClient.RadarOverlay);
        obj.addProperty("KeyPerspective", WorthClient.KeyPerspective);
        obj.addProperty("WailaMod", WorthClient.WailaMod);
        obj.addProperty("KeyZoom", WorthClient.KeyZoom);
        obj.addProperty("enableToggleZoom", WorthClient.enableToggleZoom);
        obj.addProperty("PerspectiveStartFront", WorthClient.PerspectiveStartFront);
        obj.addProperty("AutoLoginEnabled", WorthClient.AutoLoginEnabled);
        obj.addProperty("toggleScoreBoard", ScoreboardHUD.toggled);
        obj.addProperty("showNumbersScoreBoard", ScoreboardHUD.showNumbers);
        obj.addProperty("backgroundScoreBoard", ScoreboardHUD.background);
        obj.addProperty("backgroundColorScoreBoard", ScoreboardHUD.backgroundColor);
        obj.addProperty("borderScoreBoard", ScoreboardHUD.border);
        obj.addProperty("borderColorScoreBoard", ScoreboardHUD.borderColor);
        obj.addProperty("scaleScoreBoard", ScoreboardHUD.scale);
        obj.addProperty("skin3D", WorthClient.skin3D);
        obj.addProperty("pixelsThickness", WorthClient.pixelsThickness);
        obj.addProperty("timeChangerEnable", WorthClient.timeChangerEnable);
        obj.addProperty("clientTime", WorthClient.clientTime);
        obj.addProperty("AnimationsConfigEnabled", AnimationsConfig.enabled);
        obj.addProperty("AnimationsConfigblockHit17", AnimationsConfig.blockHit17);
        obj.addProperty("AnimationsConfigsmoothSwing", AnimationsConfig.smoothSwing);
        obj.addProperty("AnimationsConfigoldRod", AnimationsConfig.oldRod);
        obj.addProperty("AnimationsConfigoldBow", AnimationsConfig.oldBow);
        obj.addProperty("AnimationsConfigoldSneak", AnimationsConfig.oldSneak);
        obj.addProperty("AnimationsConfigitemTransforms", AnimationsConfig.itemTransforms);
        obj.addProperty("AnimationsConfigdamageShake", AnimationsConfig.damageShake);
        obj.addProperty("AnimationsConfighealthFlash", AnimationsConfig.healthFlash);
        obj.addProperty("AnimationsConfiguserItemWhileDigging", AnimationsConfig.userItemWhileDigging);
        obj.addProperty("AnimationsConfigalwaysSwing", AnimationsConfig.alwaysSwing);
        obj.addProperty("AnimationsConfigitemPosX", AnimationsConfig.itemPosX);
        obj.addProperty("AnimationsConfigitemPosY", AnimationsConfig.itemPosY);
        obj.addProperty("AnimationsConfigitemPosZ", AnimationsConfig.itemPosZ);
        obj.addProperty("AnimationsConfigitemScale", AnimationsConfig.itemScale);
        obj.addProperty("WblockIsBuild", WorthClient.blockIsBuild);
        obj.addProperty("WanimationPortal", WorthClient.animationPortal);
        obj.addProperty("WhelmetStyle", WorthClient.helmetStyle);
        obj.addProperty("WchestplateStyle", WorthClient.chestplateStyle);
        obj.addProperty("WleggingsStyle", WorthClient.leggingsStyle);
        obj.addProperty("WbootsStyle", WorthClient.bootsStyle);
        obj.addProperty("WmainHandStyle", WorthClient.mainHandStyle);
        obj.addProperty("KeySenabled", KeystrokesSettings.enabled);
        obj.addProperty("KeySshowClicks", KeystrokesSettings.showClicks);
        obj.addProperty("KeySshowMovement", KeystrokesSettings.showMovement);
        obj.addProperty("KeySshowSpace", KeystrokesSettings.showSpace);
        obj.addProperty("KeySuseArrows", KeystrokesSettings.useArrows);
        obj.addProperty("KeyStextShadow", KeystrokesSettings.textShadow);
        obj.addProperty("KeySborderEnabled", KeystrokesSettings.borderEnabled);
        obj.addProperty("KeySscale", KeystrokesSettings.scale);
        obj.addProperty("KeySboxSize", KeystrokesSettings.boxSize);
        obj.addProperty("KeySborderThickness", KeystrokesSettings.borderThickness);
        obj.addProperty("KeySchromaMode", KeystrokesSettings.chromaMode);
        obj.addProperty("KeyScolBack", KeystrokesSettings.backgroundDefault.getRGB());
        obj.addProperty("KeyScolPress", KeystrokesSettings.backgroundPressed.getRGB());
        obj.addProperty("KeyScolText", KeystrokesSettings.textColor.getRGB());
        obj.addProperty("KeyScolBorder", KeystrokesSettings.borderColor.getRGB());
        obj.addProperty("KeyScolTextPress", KeystrokesSettings.textPressedColor.getRGB());
        obj.addProperty("WsomReverbAnb", WorthClient.somReverbAnb);

        try (FileWriter writer = new FileWriter(FILE)) {
            new Gson().toJson(obj, writer);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void load() {
        if (!FILE.exists()) return;

        try (FileReader reader = new FileReader(FILE)) {
            JsonObject obj = new Gson().fromJson(reader, JsonObject.class);
            if (obj.has("petBlock")) WorthClient.blockPetMessages = obj.get("petBlock").getAsBoolean();
            if (obj.has("inventoryBlock")) WorthClient.blockInventoryMessages = obj.get("inventoryBlock").getAsBoolean();
            if (obj.has("announceZealot")) WorthClient.announceZealot = obj.get("announceZealot").getAsBoolean();
            if (obj.has("MsgBlockDestroyBlock")) WorthClient.MsgBlockDestroyBlock = obj.get("MsgBlockDestroyBlock").getAsBoolean();
            if (obj.has("petOverlay")) WorthClient.petOverlay = obj.get("petOverlay").getAsBoolean();
            if (obj.has("pingOverlay")) PingHUD.enabled = obj.get("pingOverlay").getAsBoolean();
            if (obj.has("pingOverlayscale")) PingHUD.scale = obj.get("pingOverlayscale").getAsByte();
            if (obj.has("pingOverlaybackground")) PingHUD.background = obj.get("pingOverlaybackground").getAsBoolean();
            if (obj.has("pingOverlaybackgroundColor")) PingHUD.backgroundColor = obj.get("pingOverlaybackgroundColor").getAsByte();
            if (obj.has("pingOverlayborder")) PingHUD.border = obj.get("pingOverlayborder").getAsBoolean();
            if (obj.has("pingOverlayborderColor")) PingHUD.borderColor = obj.get("pingOverlayborderColor").getAsByte();
            if (obj.has("pingOverlaychroma")) PingHUD.chroma = obj.get("pingOverlaychroma").getAsBoolean();
            if (obj.has("pingOverlaytextColor")) PingHUD.textColor = obj.get("pingOverlaytextColor").getAsByte();
            if (obj.has("pingOverlaytextShadow")) PingHUD.textShadow = obj.get("pingOverlaytextShadow").getAsBoolean();
            if (obj.has("fpsOverlay")) FPSHUD.enabled = obj.get("fpsOverlay").getAsBoolean();
            if (obj.has("fpsOverlayscale")) FPSHUD.scale = obj.get("fpsOverlayscale").getAsByte();
            if (obj.has("fpsOverlaybackground")) FPSHUD.background = obj.get("fpsOverlaybackground").getAsBoolean();
            if (obj.has("fpsOverlaybackgroundColor")) FPSHUD.backgroundColor = obj.get("fpsOverlaybackgroundColor").getAsByte();
            if (obj.has("fpsOverlayborder")) FPSHUD.border = obj.get("fpsOverlayborder").getAsBoolean();
            if (obj.has("fpsOverlayborderColor")) FPSHUD.borderColor = obj.get("fpsOverlayborderColor").getAsByte();
            if (obj.has("fpsOverlaychroma")) FPSHUD.chroma = obj.get("fpsOverlaychroma").getAsBoolean();
            if (obj.has("fpsOverlaytextColor")) FPSHUD.textColor = obj.get("fpsOverlaytextColor").getAsByte();
            if (obj.has("fpsOverlaytextShadow")) FPSHUD.textShadow = obj.get("fpsOverlaytextShadow").getAsBoolean();
            if (obj.has("mainHandHUDOverlay")) WorthClient.mainHandHUDOverlay = obj.get("mainHandHUDOverlay").getAsBoolean();
            if (obj.has("helmetHUDOverlay")) WorthClient.helmetHUDOverlay = obj.get("helmetHUDOverlay").getAsBoolean();
            if (obj.has("chestplateHUDOverlay")) WorthClient.chestplateHUDOverlay = obj.get("chestplateHUDOverlay").getAsBoolean();
            if (obj.has("leggingsHUDOverlay")) WorthClient.leggingsHUDOverlay = obj.get("leggingsHUDOverlay").getAsBoolean();
            if (obj.has("bootsHUDOverlay")) WorthClient.bootsHUDOverlay = obj.get("bootsHUDOverlay").getAsBoolean();
            if (obj.has("petDisplayViewOff")) WorthClient.petDisplayViewOff = obj.get("petDisplayViewOff").getAsBoolean();
            if (obj.has("viewsPetAll")) WorthClient.viewsPetAll = obj.get("viewsPetAll").getAsBoolean();
            if (obj.has("showTime")) WorthClient.showTime = obj.get("showTime").getAsBoolean();
            if (obj.has("enableCopy")) WorthClient.enableCopy = obj.get("enableCopy").getAsBoolean();
            if (obj.has("PerspectiveModToggle")) WorthClient.PerspectiveModToggle = obj.get("PerspectiveModToggle").getAsBoolean();
            if (obj.has("RadarOverlay")) WorthClient.RadarOverlay = obj.get("RadarOverlay").getAsBoolean();
            if (obj.has("ArmorsOverlays")) WorthClient.ArmorsOverlays = obj.get("ArmorsOverlays").getAsBoolean();
            if (obj.has("KeyPerspective")) WorthClient.KeyPerspective = obj.get("KeyPerspective").getAsInt();
            if (obj.has("WailaMod")) WorthClient.WailaMod = obj.get("WailaMod").getAsBoolean();
            if (obj.has("KeyZoom")) WorthClient.KeyZoom = obj.get("KeyZoom").getAsInt();
            if (obj.has("enableToggleZoom")) WorthClient.enableToggleZoom = obj.get("enableToggleZoom").getAsBoolean();
            if (obj.has("PerspectiveStartFront")) WorthClient.PerspectiveStartFront = obj.get("PerspectiveStartFront").getAsBoolean();
            if (obj.has("AutoLoginEnabled")) WorthClient.AutoLoginEnabled = obj.get("AutoLoginEnabled").getAsBoolean();
            if (obj.has("toggleScoreBoard")) ScoreboardHUD.toggled  = obj.get("toggleScoreBoard").getAsBoolean();
            if (obj.has("showNumbersScoreBoard")) ScoreboardHUD.showNumbers  = obj.get("showNumbersScoreBoard").getAsBoolean();
            if (obj.has("backgroundScoreBoard")) ScoreboardHUD.background  = obj.get("backgroundScoreBoard").getAsBoolean();
            if (obj.has("backgroundColorScoreBoard")) ScoreboardHUD.backgroundColor  = obj.get("backgroundColorScoreBoard").getAsInt();
            if (obj.has("borderScoreBoard")) ScoreboardHUD.border  = obj.get("borderScoreBoard").getAsBoolean();
            if (obj.has("borderColorScoreBoard")) ScoreboardHUD.borderColor  = obj.get("borderColorScoreBoard").getAsInt();
            if (obj.has("scaleScoreBoard")) ScoreboardHUD.scale  = obj.get("scaleScoreBoard").getAsInt();
            if (obj.has("skin3D")) WorthClient.skin3D  = obj.get("skin3D").getAsBoolean();
            if (obj.has("pixelsThickness")) WorthClient.pixelsThickness  = obj.get("pixelsThickness").getAsInt();
            if (obj.has("timeChangerEnable")) WorthClient.timeChangerEnable  = obj.get("timeChangerEnable").getAsBoolean();
            if (obj.has("clientTime")) WorthClient.clientTime  = obj.get("clientTime").getAsInt();
            if (obj.has("AnimationsConfigEnabled")) AnimationsConfig.enabled  = obj.get("AnimationsConfigEnabled").getAsBoolean();
            if (obj.has("AnimationsConfigblockHit17")) AnimationsConfig.blockHit17  = obj.get("AnimationsConfigblockHit17").getAsBoolean();
            if (obj.has("AnimationsConfigsmoothSwing")) AnimationsConfig.smoothSwing  = obj.get("AnimationsConfigsmoothSwing").getAsBoolean();
            if (obj.has("AnimationsConfigoldRod")) AnimationsConfig.oldRod  = obj.get("AnimationsConfigoldRod").getAsBoolean();
            if (obj.has("AnimationsConfigoldBow")) AnimationsConfig.oldBow  = obj.get("AnimationsConfigoldBow").getAsBoolean();
            if (obj.has("AnimationsConfigoldSneak")) AnimationsConfig.oldSneak  = obj.get("AnimationsConfigoldSneak").getAsBoolean();
            if (obj.has("AnimationsConfigitemTransforms")) AnimationsConfig.itemTransforms  = obj.get("AnimationsConfigitemTransforms").getAsBoolean();
            if (obj.has("AnimationsConfigdamageShake")) AnimationsConfig.damageShake  = obj.get("AnimationsConfigdamageShake").getAsBoolean();
            if (obj.has("AnimationsConfighealthFlash")) AnimationsConfig.healthFlash  = obj.get("AnimationsConfighealthFlash").getAsBoolean();
            if (obj.has("AnimationsConfiguserItemWhileDigging")) AnimationsConfig.userItemWhileDigging  = obj.get("AnimationsConfiguserItemWhileDigging").getAsBoolean();
            if (obj.has("AnimationsConfigalwaysSwing")) AnimationsConfig.alwaysSwing  = obj.get("AnimationsConfigalwaysSwing").getAsBoolean();
            if (obj.has("AnimationsConfigitemPosX")) AnimationsConfig.itemPosX  = obj.get("AnimationsConfigitemPosX").getAsInt();
            if (obj.has("AnimationsConfigitemPosY")) AnimationsConfig.itemPosY  = obj.get("AnimationsConfigitemPosY").getAsInt();
            if (obj.has("AnimationsConfigitemPosZ")) AnimationsConfig.itemPosZ  = obj.get("AnimationsConfigitemPosZ").getAsInt();
            if (obj.has("AnimationsConfigitemScale")) AnimationsConfig.itemScale  = obj.get("AnimationsConfigitemScale").getAsInt();
            if (obj.has("WblockIsBuild")) WorthClient.blockIsBuild  = obj.get("WblockIsBuild").getAsBoolean();
            if (obj.has("WanimationPortal")) WorthClient.animationPortal  = obj.get("WanimationPortal").getAsBoolean();
            if (obj.has("WhelmetStyle")) WorthClient.helmetStyle  = obj.get("WhelmetStyle").getAsString();
            if (obj.has("WchestplateStyle")) WorthClient.chestplateStyle  = obj.get("WchestplateStyle").getAsString();
            if (obj.has("WleggingsStyle")) WorthClient.leggingsStyle  = obj.get("WleggingsStyle").getAsString();
            if (obj.has("WbootsStyle")) WorthClient.bootsStyle  = obj.get("WbootsStyle").getAsString();
            if (obj.has("WmainHandStyle")) WorthClient.mainHandStyle  = obj.get("WmainHandStyle").getAsString();
            if (obj.has("KeySenabled")) KeystrokesSettings.enabled = obj.get("KeySenabled").getAsBoolean();
            if (obj.has("KeySshowClicks")) KeystrokesSettings.showClicks = obj.get("KeySshowClicks").getAsBoolean();
            if (obj.has("KeySshowMovement")) KeystrokesSettings.showMovement = obj.get("KeySshowMovement").getAsBoolean();
            if (obj.has("KeySshowSpace")) KeystrokesSettings.showSpace = obj.get("KeySshowSpace").getAsBoolean();
            if (obj.has("KeySuseArrows")) KeystrokesSettings.useArrows = obj.get("KeySuseArrows").getAsBoolean();
            if (obj.has("KeyStextShadow")) KeystrokesSettings.textShadow = obj.get("KeyStextShadow").getAsBoolean();
            if (obj.has("KeySborderEnabled")) KeystrokesSettings.borderEnabled = obj.get("KeySborderEnabled").getAsBoolean();
            if (obj.has("KeySscale")) KeystrokesSettings.scale = obj.get("KeySscale").getAsFloat();
            if (obj.has("KeySboxSize")) KeystrokesSettings.boxSize = obj.get("KeySboxSize").getAsFloat();
            if (obj.has("KeySborderThickness")) KeystrokesSettings.borderThickness = obj.get("KeySborderThickness").getAsFloat();
            if (obj.has("KeySchromaMode")) KeystrokesSettings.chromaMode = obj.get("KeySchromaMode").getAsBoolean();
            if (obj.has("KeyScolBack")) KeystrokesSettings.backgroundDefault = new Color(obj.get("KeyScolBack").getAsInt(), true);
            if (obj.has("KeyScolPress")) KeystrokesSettings.backgroundPressed = new Color(obj.get("KeyScolPress").getAsInt(), true);
            if (obj.has("KeyScolText")) KeystrokesSettings.textColor = new Color(obj.get("KeyScolText").getAsInt(), true);
            if (obj.has("KeyScolBorder")) KeystrokesSettings.borderColor = new Color(obj.get("KeyScolBorder").getAsInt(), true);
            if (obj.has("KeyScolTextPress")) KeystrokesSettings.textPressedColor = new Color(obj.get("KeyScolTextPress").getAsInt(), true);
            if (obj.has("WsomReverbAnb")) WorthClient.somReverbAnb = obj.get("WsomReverbAnb").getAsBoolean();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}